PUT http://localhost:8080/categories/move
Content-Type: application/json

{
  "targetIdx": "8",
  "destIdx": "",
  "sequence": "1"
}
### destIdx 가 "" 일 경우에는 타켓 카티고리를 루트로 보내는 요청

###
GET http://localhost:8080/categories

###